## lightning.pytorch==2.0.8
data:
#  targetName: TEST #provide data.targetName as cmd argument
#  halfset: 0  #provide data.halfset as cmd argument
  benchmarkDir: ~/tmp/cryoSupervisedDataset
  image_size: 256
  train_validation_split:
    - 0.7
    - 0.3
  batch_size: 32
  image_size_factor_for_crop: 0.25
  num_data_workers: 0
